/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.IntegrationModel;
import OICApi.OicRestApi;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mherrera
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Benvenido: " + OicRestApi.user);
        hideElemnets();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuTblTst2 = new javax.swing.JPopupMenu();
        itemMigrar_uat2 = new javax.swing.JMenuItem();
        itemMigrar_prd = new javax.swing.JMenuItem();
        jpContent = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpIntegrations = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1TST2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_integraciones = new javax.swing.JTable();
        pb_tst2 = new javax.swing.JProgressBar();
        lblIntegraTST2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblinfotst2 = new javax.swing.JLabel();
        lblPreloaderExport = new javax.swing.JLabel();
        jPanelUAT2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_int_uat2 = new javax.swing.JTable();
        pb_uat2 = new javax.swing.JProgressBar();
        lblIntegraUAT2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblinfoUat2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuConfig = new javax.swing.JMenu();
        itemCredenciales = new javax.swing.JMenuItem();
        mnuOicApi = new javax.swing.JMenu();
        itemList = new javax.swing.JMenuItem();

        itemMigrar_uat2.setText("Migrar a: UAT2");
        itemMigrar_uat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMigrar_uat2ActionPerformed(evt);
            }
        });
        mnuTblTst2.add(itemMigrar_uat2);

        itemMigrar_prd.setText("Migrar a: PRD");
        mnuTblTst2.add(itemMigrar_prd);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("HELLO WORDL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1TST2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1TST2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1TST2ComponentShown(evt);
            }
        });

        tbl_integraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_integraciones.setComponentPopupMenu(mnuTblTst2);
        jScrollPane1.setViewportView(tbl_integraciones);

        pb_tst2.setIndeterminate(true);

        lblIntegraTST2.setText("Total Integraciones: 0");

        jButton1.setText("Cargar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPreloaderExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1495 (5).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1TST2Layout = new javax.swing.GroupLayout(jPanel1TST2);
        jPanel1TST2.setLayout(jPanel1TST2Layout);
        jPanel1TST2Layout.setHorizontalGroup(
            jPanel1TST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1TST2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1TST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1TST2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblIntegraTST2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(pb_tst2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(372, Short.MAX_VALUE))
                    .addGroup(jPanel1TST2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblinfotst2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPreloaderExport)
                        .addGap(84, 84, 84))
                    .addComponent(jScrollPane1)))
        );
        jPanel1TST2Layout.setVerticalGroup(
            jPanel1TST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1TST2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1TST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1TST2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblinfotst2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPreloaderExport, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1TST2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_tst2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntegraTST2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("TST2", jPanel1TST2);

        jPanelUAT2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelUAT2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelUAT2ComponentShown(evt);
            }
        });

        tbl_int_uat2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_int_uat2);

        pb_uat2.setIndeterminate(true);

        lblIntegraUAT2.setText("Total Integraciones: 0");

        jButton2.setText("Cargar Datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUAT2Layout = new javax.swing.GroupLayout(jPanelUAT2);
        jPanelUAT2.setLayout(jPanelUAT2Layout);
        jPanelUAT2Layout.setHorizontalGroup(
            jPanelUAT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUAT2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUAT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUAT2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblIntegraUAT2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(pb_uat2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(372, Short.MAX_VALUE))
                    .addGroup(jPanelUAT2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanelUAT2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblinfoUat2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelUAT2Layout.setVerticalGroup(
            jPanelUAT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUAT2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUAT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUAT2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblinfoUat2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelUAT2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_uat2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntegraUAT2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("UAT2", jPanelUAT2);

        jTabbedPane1.setSelectedComponent(jPanel1TST2);

        javax.swing.GroupLayout jpIntegrationsLayout = new javax.swing.GroupLayout(jpIntegrations);
        jpIntegrations.setLayout(jpIntegrationsLayout);
        jpIntegrationsLayout.setHorizontalGroup(
            jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIntegrationsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jpIntegrationsLayout.setVerticalGroup(
            jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIntegrationsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpContent.setLayer(jPanel1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jpContent.setLayer(jpIntegrations, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIntegrations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIntegrations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuConfig.setText("Configuración");

        itemCredenciales.setText("Configurar credenciales de aplicación");
        mnuConfig.add(itemCredenciales);

        jMenuBar1.add(mnuConfig);

        mnuOicApi.setText("Oic Api");

        itemList.setText("Listar Integraciones");
        itemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListActionPerformed(evt);
            }
        });
        mnuOicApi.add(itemList);

        jMenuBar1.add(mnuOicApi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpContent)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListActionPerformed
        jPanel1.setVisible(false);
        jpIntegrations.setVisible(true);
//        MiHilo miHilo = new MiHilo("TST2", tbl_integraciones, lblIntegraTST2, pb_tst2);
//        miHilo.start();      
    }//GEN-LAST:event_itemListActionPerformed

    private void jPanel1TST2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1TST2ComponentShown
        System.out.println("jPanel1TST2ComponentShown");
        if (tbl_integraciones.getRowCount() == 0) {
            if (hiloOcupado) {
                jTabbedPane1.setSelectedComponent(currentPanel);
                lblinfotst2.setText("Espere a que el proceso termine para inicar otro");
            } else {
                MiHilo miHilo = new MiHilo("TST2", tbl_integraciones, lblIntegraTST2, pb_tst2, jPanel1TST2);
                miHilo.start();
            }
        }

    }//GEN-LAST:event_jPanel1TST2ComponentShown

    private void jPanelUAT2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelUAT2ComponentShown
        // TODO add your handling code here:
        if (tbl_int_uat2.getRowCount() == 0) {
            if (hiloOcupado) {
                jTabbedPane1.setSelectedComponent(currentPanel);
                lblinfoUat2.setText("Espere a que el proceso termine para inicar otro");
            } else {
                MiHilo miHilo = new MiHilo("UAT2", tbl_int_uat2, lblIntegraUAT2, pb_uat2, jPanelUAT2);
                miHilo.start();
            }
        }
    }//GEN-LAST:event_jPanelUAT2ComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MiHilo miHilo = new MiHilo("TST2", tbl_integraciones, lblIntegraTST2, pb_tst2, jPanel1TST2);
        miHilo.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MiHilo miHilo = new MiHilo("UAT2", tbl_int_uat2, lblIntegraUAT2, pb_uat2, jPanelUAT2);
        miHilo.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void itemMigrar_uat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMigrar_uat2ActionPerformed
        int row = tbl_integraciones.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
            return;
        }
        String value = tbl_integraciones.getModel().getValueAt(row, 0).toString();
        String name = tbl_integraciones.getModel().getValueAt(row, 1).toString() + ".iar";
        String version = tbl_integraciones.getModel().getValueAt(row, 4).toString();
        tbl_integraciones.clearSelection();
        ExportarIntegracion hexportar = new ExportarIntegracion(value, name.replaceAll(" ", "_"), "TST2", version);
        hexportar.start();
    }//GEN-LAST:event_itemMigrar_uat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCredenciales;
    private javax.swing.JMenuItem itemList;
    private javax.swing.JMenuItem itemMigrar_prd;
    private javax.swing.JMenuItem itemMigrar_uat2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel1TST2;
    private javax.swing.JPanel jPanelUAT2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLayeredPane jpContent;
    private javax.swing.JPanel jpIntegrations;
    private javax.swing.JLabel lblIntegraTST2;
    private javax.swing.JLabel lblIntegraUAT2;
    private javax.swing.JLabel lblPreloaderExport;
    private javax.swing.JLabel lblinfoUat2;
    private javax.swing.JLabel lblinfotst2;
    private javax.swing.JMenu mnuConfig;
    private javax.swing.JMenu mnuOicApi;
    private javax.swing.JPopupMenu mnuTblTst2;
    private javax.swing.JProgressBar pb_tst2;
    private javax.swing.JProgressBar pb_uat2;
    private javax.swing.JTable tbl_int_uat2;
    private javax.swing.JTable tbl_integraciones;
    // End of variables declaration//GEN-END:variables

    //CustomVars
    boolean hiloOcupado = false;
    JPanel currentPanel;

    private void hideElemnets() {
        jpIntegrations.setVisible(false);
        pb_tst2.setVisible(false);
        pb_uat2.setVisible(false);
        lblPreloaderExport.setVisible(false);
    }

    private void cargarIntegraciones(String env, JTable table, JLabel lbl, JProgressBar pb, JPanel curPanel) {

        System.out.println("cargando");

        hiloOcupado = true;
        if (currentPanel == null) {
            currentPanel = curPanel;
        }

        pb.setVisible(true);
        IntegrationModel im = new IntegrationModel();
        Map<String, Object> respuesta = im.getIntegrations(env);
        int total = (int) respuesta.get("total");
        lbl.setText("Total Integraciones: " + total);

        JsonArray list = (JsonArray) respuesta.get("integraciones");
        DefaultTableModel modeloTabla = new DefaultTableModel();
        // Agregar columnas a nuestro modelo de tabla
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("NAME");
        modeloTabla.addColumn("CODE");
        modeloTabla.addColumn("ENV");
        modeloTabla.addColumn("VERSION");
        for (JsonElement jsonElement : list) {
            JsonObject jsonObject = jsonElement.getAsJsonObject();
            String ID = jsonObject.get("id").getAsString();
            String NAME = jsonObject.get("name").getAsString();
            String CODE = jsonObject.get("code").getAsString();
            String VERSION = jsonObject.get("version").getAsString();
            modeloTabla.addRow(new Object[]{ID, NAME, CODE, env, VERSION});
        }
// Asignar el modelo de tabla a nuestro JTable
        table.setModel(modeloTabla);
        table.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        table.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        table.getColumnModel().getColumn(0).setPreferredWidth(0);
        table.getColumnModel().getColumn(0).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setMinWidth(0);
        table.getColumnModel().getColumn(3).setMaxWidth(100);
        table.getColumnModel().getColumn(3).setMinWidth(100);
        table.getColumnModel().getColumn(4).setMaxWidth(120);
        table.getColumnModel().getColumn(4).setMinWidth(120);

        table.setModel(modeloTabla);
        pb.setVisible(false);
        hiloOcupado = false;
        currentPanel = null;
        lblinfoUat2.setText("");
        lblinfotst2.setText("");

    }

    //Hilos
    public class MiHilo extends Thread {

        String ambiente;
        JTable table;
        JLabel lbl;
        JProgressBar pb;
        JPanel curPanel;

        public MiHilo(String ambiente, JTable table, JLabel lbl, JProgressBar pb, JPanel curPanel) {
            this.ambiente = ambiente;
            this.table = table;
            this.lbl = lbl;
            this.pb = pb;
            this.curPanel = curPanel;
        }

        @Override
        public void run() {
            cargarIntegraciones(ambiente, table, lbl, pb, curPanel);
        }
    }

    public class ExportarIntegracion extends Thread {

        String ambiente;
        String id;
        String nombre;
        String version;

        public ExportarIntegracion(String id, String nombre, String ambiente, String version) {
            this.ambiente = ambiente;
            this.id = id;
            this.nombre = nombre;
            this.version = version;
        }

        @Override
        public void run() {
            lblPreloaderExport.setVisible(true);
            OicRestApi oic = new OicRestApi();
            boolean r = oic.exportIntegration(id, nombre, ambiente);
            System.out.println("respuesta r " + r);
            lblPreloaderExport.setVisible(false);
            if (r) {
                ImportarIntegracion hiloImportar = new ImportarIntegracion(id, nombre, ambiente, version);
                hiloImportar.start();
            }
        }
    }

    public class ImportarIntegracion extends Thread {

        String ambiente;
        String id;
        String nombre;
        String version;

        public ImportarIntegracion(String id, String nombre, String ambiente, String version) {
            this.ambiente = ambiente;
            this.id = id;
            this.nombre = nombre;
            this.version = version;
            System.out.println("importando");
        }

        @Override
        public void run() {

            //Refrescar el copnector con las credenciales
            //Activar integarcione
            lblPreloaderExport.setVisible(true);
            OicRestApi oic = new OicRestApi();
            int response = oic.importIntegration(nombre, "UAT2", "POST");
            System.out.println("response 2 " + response);
            //poner logica para response 200
            if (response == 409) {
                int result = JOptionPane.showConfirmDialog(MainForm.this, "¿La integración " + nombre + " V(" + version + ") ya existe, desea reemplazarla?",
                        "Confirmación..!",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    response = oic.importIntegration(nombre, "UAT2", "PUT");
                    if (response == 200) {
                        JOptionPane.showMessageDialog(MainForm.this, "Integración importada, actualizada y activada correctamente..!");
                    }
                    //Poner resto de logica
                }
                if (result == JOptionPane.NO_OPTION) {
                    System.out.println("No option");
                }
            }
            lblPreloaderExport.setVisible(false);
        }

    }
}
