/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.ConectoresModel;
import Models.IntegrationModel;
import Models.LookupsModel;
import OICApi.OicRestApi;
import Utils.Utils;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.MenuElement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mherrera
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        try {
            setIconImage(ImageIO.read(new File("src\\images\\Icono.png")));
        } catch (IOException ex) {
            System.out.println("error " + ex);
        }
        setLocationRelativeTo(null);
        setTitle("Benvenido: " + OicRestApi.user);
        Utils.clearDirectory("downloads");
        hideElemnets();
        cargarTablaAmbientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuTblAmbiente = new javax.swing.JPopupMenu();
        itemSeletedEnv = new javax.swing.JMenuItem();
        mnuTblAmbiente2 = new javax.swing.JPopupMenu();
        itemSeletedEnv1 = new javax.swing.JMenuItem();
        mnuTblAmbiente3 = new javax.swing.JPopupMenu();
        itemSeletedEnv2 = new javax.swing.JMenuItem();
        mnuTblConectores = new javax.swing.JPopupMenu();
        itemTestConection = new javax.swing.JMenuItem();
        itemConfigCredencial = new javax.swing.JMenuItem();
        jpContent = new javax.swing.JLayeredPane();
        jpLookupTables = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblEnvironment3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLookups = new javax.swing.JTable();
        pb_tst2_lookups = new javax.swing.JProgressBar();
        lblLookups = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        lblinfotstLookups = new javax.swing.JLabel();
        lblPreloaderLookups = new javax.swing.JLabel();
        lblCurEnv3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jpIntegrations = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblEnvironment = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_integraciones = new javax.swing.JTable();
        pb_tst2 = new javax.swing.JProgressBar();
        lblIntegraTST2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblinfotst2 = new javax.swing.JLabel();
        lblPreloaderExport = new javax.swing.JLabel();
        cboStatusIntg = new javax.swing.JComboBox<>();
        lblCurEnv = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpConectores = new javax.swing.JPanel();
        cboStatusIntg1 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblEnvironment2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConectTST2 = new javax.swing.JTable();
        pb_tst2_con = new javax.swing.JProgressBar();
        lboConectorsTST2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblinfotstCon = new javax.swing.JLabel();
        lblPreloaderUpdConector = new javax.swing.JLabel();
        lblCurEnv2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuConfig = new javax.swing.JMenu();
        itemCredenciales = new javax.swing.JMenuItem();
        itemUrlOic = new javax.swing.JMenuItem();
        mnuOicApi = new javax.swing.JMenu();
        itemConnections = new javax.swing.JMenuItem();
        itemListLookups = new javax.swing.JMenuItem();
        itemList = new javax.swing.JMenuItem();

        itemSeletedEnv.setText("Seleccionar");
        itemSeletedEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSeletedEnvActionPerformed(evt);
            }
        });
        mnuTblAmbiente.add(itemSeletedEnv);

        itemSeletedEnv1.setText("Seleccionar");
        itemSeletedEnv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSeletedEnv1ActionPerformed(evt);
            }
        });
        mnuTblAmbiente2.add(itemSeletedEnv1);

        itemSeletedEnv2.setText("Seleccionar");
        itemSeletedEnv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSeletedEnv2ActionPerformed(evt);
            }
        });
        mnuTblAmbiente3.add(itemSeletedEnv2);

        itemTestConection.setText("Probar Conexión");
        itemTestConection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTestConectionActionPerformed(evt);
            }
        });
        mnuTblConectores.add(itemTestConection);

        itemConfigCredencial.setText("Reconfigurar Credenciales");
        itemConfigCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConfigCredencialActionPerformed(evt);
            }
        });
        mnuTblConectores.add(itemConfigCredencial);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEnvironment3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEnvironment3.setComponentPopupMenu(mnuTblAmbiente3);
        jScrollPane7.setViewportView(tblEnvironment3);

        tblLookups.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tblLookups);

        pb_tst2_lookups.setIndeterminate(true);

        lblLookups.setText("Total Lookups: 0");

        jButton4.setText("Cargar Datos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lblPreloaderLookups.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1494.gif"))); // NOI18N

        lblCurEnv3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurEnv3.setText("Ambiente Seleccionado: --");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Listado de Lookups");

        javax.swing.GroupLayout jpLookupTablesLayout = new javax.swing.GroupLayout(jpLookupTables);
        jpLookupTables.setLayout(jpLookupTablesLayout);
        jpLookupTablesLayout.setHorizontalGroup(
            jpLookupTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLookupTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLookupTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpLookupTablesLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpLookupTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCurEnv3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpLookupTablesLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPreloaderLookups))
                            .addComponent(lblinfotstLookups, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpLookupTablesLayout.createSequentialGroup()
                        .addComponent(lblLookups, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(pb_tst2_lookups, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 384, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jpLookupTablesLayout.setVerticalGroup(
            jpLookupTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLookupTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLookupTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpLookupTablesLayout.createSequentialGroup()
                        .addComponent(lblCurEnv3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(jpLookupTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPreloaderLookups, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblinfotstLookups, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jpLookupTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_tst2_lookups, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLookups))
                .addGap(27, 27, 27))
        );

        tblEnvironment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEnvironment.setComponentPopupMenu(mnuTblAmbiente);
        jScrollPane5.setViewportView(tblEnvironment);

        tbl_integraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_integraciones);

        pb_tst2.setIndeterminate(true);

        lblIntegraTST2.setText("Total Integraciones: 0");

        jButton1.setText("Cargar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPreloaderExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1494.gif"))); // NOI18N

        cboStatusIntg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Estado", "ACTIVATED", "CONFIGURED", "INPROGRESS" }));

        lblCurEnv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurEnv.setText("Ambiente Seleccionado: --");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Listado de Integraciones");

        javax.swing.GroupLayout jpIntegrationsLayout = new javax.swing.GroupLayout(jpIntegrations);
        jpIntegrations.setLayout(jpIntegrationsLayout);
        jpIntegrationsLayout.setHorizontalGroup(
            jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIntegrationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIntegrationsLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinfotst2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpIntegrationsLayout.createSequentialGroup()
                                .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboStatusIntg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpIntegrationsLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(lblPreloaderExport))
                                    .addGroup(jpIntegrationsLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCurEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jpIntegrationsLayout.createSequentialGroup()
                        .addComponent(lblIntegraTST2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(pb_tst2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpIntegrationsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpIntegrationsLayout.setVerticalGroup(
            jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIntegrationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpIntegrationsLayout.createSequentialGroup()
                        .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboStatusIntg)
                            .addComponent(lblCurEnv, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(lblPreloaderExport, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblinfotst2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 486, Short.MAX_VALUE)
                .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_tst2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntegraTST2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28))
            .addGroup(jpIntegrationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpIntegrationsLayout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        cboStatusIntg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Estado", "CONFIGURED", "INPROGRESS" }));

        tblEnvironment2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblEnvironment2.setComponentPopupMenu(mnuTblAmbiente2);
        jScrollPane6.setViewportView(tblEnvironment2);

        tblConectTST2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblConectTST2.setComponentPopupMenu(mnuTblConectores);
        jScrollPane3.setViewportView(tblConectTST2);

        pb_tst2_con.setIndeterminate(true);

        lboConectorsTST2.setText("Total Conectores: 0");

        jButton3.setText("Cargar Datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblPreloaderUpdConector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1494.gif"))); // NOI18N

        lblCurEnv2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCurEnv2.setText("Ambiente Seleccionado: --");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Listado de Conectores");

        javax.swing.GroupLayout jpConectoresLayout = new javax.swing.GroupLayout(jpConectores);
        jpConectores.setLayout(jpConectoresLayout);
        jpConectoresLayout.setHorizontalGroup(
            jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConectoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConectoresLayout.createSequentialGroup()
                        .addGroup(jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpConectoresLayout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpConectoresLayout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPreloaderUpdConector))
                                    .addComponent(lblinfotstCon, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpConectoresLayout.createSequentialGroup()
                                        .addComponent(cboStatusIntg1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCurEnv2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpConectoresLayout.createSequentialGroup()
                                .addComponent(lboConectorsTST2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167)
                                .addComponent(pb_tst2_con, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(jpConectoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );
        jpConectoresLayout.setVerticalGroup(
            jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConectoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpConectoresLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(lblPreloaderUpdConector, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblinfotstCon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboStatusIntg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCurEnv2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jpConectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_tst2_con, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lboConectorsTST2))
                .addGap(27, 27, 27))
        );

        jLabel1.setText("HELLO WORDL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1)
                .addContainerGap(425, Short.MAX_VALUE))
        );

        jpContent.setLayer(jpLookupTables, javax.swing.JLayeredPane.PALETTE_LAYER);
        jpContent.setLayer(jpIntegrations, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpContent.setLayer(jpConectores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jpContent.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIntegrations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpConectores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpContentLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpLookupTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpIntegrations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpConectores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpLookupTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnuConfig.setText("Configuración");

        itemCredenciales.setText("Configurar credenciales de aplicación");
        itemCredenciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCredencialesActionPerformed(evt);
            }
        });
        mnuConfig.add(itemCredenciales);

        itemUrlOic.setText("Configurar Url´s de OIC");
        itemUrlOic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUrlOicActionPerformed(evt);
            }
        });
        mnuConfig.add(itemUrlOic);

        jMenuBar1.add(mnuConfig);

        mnuOicApi.setText("Oic Api");

        itemConnections.setLabel("Listar Conectores");
        itemConnections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConnectionsActionPerformed(evt);
            }
        });
        mnuOicApi.add(itemConnections);
        itemConnections.getAccessibleContext().setAccessibleDescription("");

        itemListLookups.setText("Listar Lookups");
        itemListLookups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListLookupsActionPerformed(evt);
            }
        });
        mnuOicApi.add(itemListLookups);

        itemList.setText("Listar Integraciones");
        itemList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListActionPerformed(evt);
            }
        });
        mnuOicApi.add(itemList);

        jMenuBar1.add(mnuOicApi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListActionPerformed
        jPanel1.setVisible(false);
        jpConectores.setVisible(false);
        jpLookupTables.setVisible(false);
        jpIntegrations.setVisible(true);
//        MiHilo miHilo = new MiHilo("TST2", tbl_integraciones, lblIntegraTST2, pb_tst2);
//        miHilo.start();      
    }//GEN-LAST:event_itemListActionPerformed

    private void itemUrlOicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUrlOicActionPerformed
        ConfigUrlOic cuo = new ConfigUrlOic();
        cuo.setVisible(true);
    }//GEN-LAST:event_itemUrlOicActionPerformed

    private void itemCredencialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCredencialesActionPerformed
        ConfigCredentials cc = new ConfigCredentials();
        cc.setVisible(true);
    }//GEN-LAST:event_itemCredencialesActionPerformed

    private void itemConnectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConnectionsActionPerformed
        jPanel1.setVisible(false);
        jpIntegrations.setVisible(false);
        jpLookupTables.setVisible(false);
        jpConectores.setVisible(true);
        selectedEnv = "";
    }//GEN-LAST:event_itemConnectionsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (selectedEnv.equals("")) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un ambiente..!");
            return;
        }
        String status = cboStatusIntg1.getSelectedItem().toString();
        MiHiloCon cargarConectores = new MiHiloCon(selectedEnv, status);
        cargarConectores.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (selectedEnv.equals("")) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un ambiente..!");
            return;
        }
        for (MenuElement menuItem : mnuTblTst2.getSubElements()) {
            if (menuItem instanceof MenuElement) {
                JMenuItem item = (JMenuItem) menuItem;
                if (item.getText().split(":")[1].trim().equals(selectedEnv)) {
                    item.setVisible(false);
                } else {
                    item.setVisible(true);
                }
            }
        }
        String status = cboStatusIntg.getSelectedItem().toString();
        MiHilo miHilo = new MiHilo(selectedEnv + "", tbl_integraciones, lblIntegraTST2, pb_tst2, status);
        miHilo.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemSeletedEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSeletedEnvActionPerformed
        int row = tblEnvironment.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
            return;
        }
        String value = tblEnvironment.getModel().getValueAt(row, 0).toString();
        selectedEnv = value;
        lblCurEnv.setText("Ambiente Seleccionado: " + value);
    }//GEN-LAST:event_itemSeletedEnvActionPerformed

    private void itemSeletedEnv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSeletedEnv1ActionPerformed
        int row = tblEnvironment2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
            return;
        }
        String value = tblEnvironment2.getModel().getValueAt(row, 0).toString();
        selectedEnv = value;
        lblCurEnv2.setText("Ambiente Seleccionado: " + value);
    }//GEN-LAST:event_itemSeletedEnv1ActionPerformed

    private void itemConfigCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConfigCredencialActionPerformed
        int row = tblConectTST2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
            return;
        }
        String id = tblConectTST2.getModel().getValueAt(row, 0).toString();
        String env = tblConectTST2.getModel().getValueAt(row, 3).toString();

        ConfigConector hiloUpdate = new ConfigConector(id, env, 1);
        hiloUpdate.start();
    }//GEN-LAST:event_itemConfigCredencialActionPerformed

    private void itemTestConectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTestConectionActionPerformed
        int row = tblConectTST2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
            return;
        }
        String id = tblConectTST2.getModel().getValueAt(row, 0).toString();
        String env = tblConectTST2.getModel().getValueAt(row, 3).toString();
        ConfigConector hiloUpdate = new ConfigConector(id, env, 2);
        hiloUpdate.start();
    }//GEN-LAST:event_itemTestConectionActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (selectedEnv.equals("")) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar un ambiente..!");
            return;
        }
        for (MenuElement menuItem : mnuTblLookups.getSubElements()) {
            if (menuItem instanceof MenuElement) {
                JMenuItem item = (JMenuItem) menuItem;
                if (item.getText().split(":")[1].trim().equals(selectedEnv)) {
                    item.setVisible(false);
                } else {
                    item.setVisible(true);
                }
            }
        }
        HiloLookups cargarLookups = new HiloLookups(selectedEnv, "");
        cargarLookups.start();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void itemListLookupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListLookupsActionPerformed
        jPanel1.setVisible(false);
        jpIntegrations.setVisible(false);
        jpConectores.setVisible(false);
        jpLookupTables.setVisible(true);
        selectedEnv = "";
    }//GEN-LAST:event_itemListLookupsActionPerformed

    private void itemSeletedEnv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSeletedEnv2ActionPerformed
        int row = tblEnvironment3.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
            return;
        }
        String value = tblEnvironment3.getModel().getValueAt(row, 0).toString();
        selectedEnv = value;
        lblCurEnv3.setText("Ambiente Seleccionado: " + value);
    }//GEN-LAST:event_itemSeletedEnv2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboStatusIntg;
    private javax.swing.JComboBox<String> cboStatusIntg1;
    private javax.swing.JMenuItem itemConfigCredencial;
    private javax.swing.JMenuItem itemConnections;
    private javax.swing.JMenuItem itemCredenciales;
    private javax.swing.JMenuItem itemList;
    private javax.swing.JMenuItem itemListLookups;
    private javax.swing.JMenuItem itemSeletedEnv;
    private javax.swing.JMenuItem itemSeletedEnv1;
    private javax.swing.JMenuItem itemSeletedEnv2;
    private javax.swing.JMenuItem itemTestConection;
    private javax.swing.JMenuItem itemUrlOic;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel jpConectores;
    private javax.swing.JLayeredPane jpContent;
    private javax.swing.JPanel jpIntegrations;
    private javax.swing.JPanel jpLookupTables;
    private javax.swing.JLabel lblCurEnv;
    private javax.swing.JLabel lblCurEnv2;
    private javax.swing.JLabel lblCurEnv3;
    private javax.swing.JLabel lblIntegraTST2;
    private javax.swing.JLabel lblLookups;
    private javax.swing.JLabel lblPreloaderExport;
    private javax.swing.JLabel lblPreloaderLookups;
    private javax.swing.JLabel lblPreloaderUpdConector;
    private javax.swing.JLabel lblinfotst2;
    private javax.swing.JLabel lblinfotstCon;
    private javax.swing.JLabel lblinfotstLookups;
    private javax.swing.JLabel lboConectorsTST2;
    private javax.swing.JMenu mnuConfig;
    private javax.swing.JMenu mnuOicApi;
    private javax.swing.JPopupMenu mnuTblAmbiente;
    private javax.swing.JPopupMenu mnuTblAmbiente2;
    private javax.swing.JPopupMenu mnuTblAmbiente3;
    private javax.swing.JPopupMenu mnuTblConectores;
    private javax.swing.JProgressBar pb_tst2;
    private javax.swing.JProgressBar pb_tst2_con;
    private javax.swing.JProgressBar pb_tst2_lookups;
    private javax.swing.JTable tblConectTST2;
    private javax.swing.JTable tblEnvironment;
    private javax.swing.JTable tblEnvironment2;
    private javax.swing.JTable tblEnvironment3;
    private javax.swing.JTable tblLookups;
    private javax.swing.JTable tbl_integraciones;
    // End of variables declaration//GEN-END:variables

    //CustomVars
    private String selectedEnv = "";
    JPopupMenu mnuTblTst2 = new JPopupMenu();
    JPopupMenu mnuTblLookups = new JPopupMenu();//crear popou para la tabla de lookups  

    //Cargar tablas Ambientes y popups
    private void cargarTablaAmbientes() {
        PopupMenuListener listener = new PopupMenuListener();
        PopupMenuListenerLookups listenerLookups = new PopupMenuListenerLookups();
        DefaultTableModel modeloTabla = new DefaultTableModel();
        // Agregar columnas a nuestro modelo de tabla
        modeloTabla.addColumn("AMBIENTE");
        Map<String, String> urlsMap = Utils.leerArchivoProperties();
        for (Map.Entry<String, String> entry : urlsMap.entrySet()) {
            modeloTabla.addRow(new Object[]{entry.getKey()});
            JMenuItem elemento = new JMenuItem("Migrar a: " + entry.getKey());
            JMenuItem elemento2 = new JMenuItem("Migrar a: " + entry.getKey());
            elemento.addActionListener(listener);
            elemento2.addActionListener(listenerLookups);
            mnuTblTst2.add(elemento);
            mnuTblLookups.add(elemento2);
        }
        tbl_integraciones.setComponentPopupMenu(mnuTblTst2);
        tblLookups.setComponentPopupMenu(mnuTblLookups);
        // Asignar el modelo de tabla a nuestro JTable
        tblEnvironment.setModel(modeloTabla);
        tblEnvironment2.setModel(modeloTabla);
        tblEnvironment3.setModel(modeloTabla);
    }

    class PopupMenuListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            JMenuItem menuItem = (JMenuItem) e.getSource();
            String[] targetEnvPart = menuItem.getText().split(":");
            String[] sourceEnvpart = lblCurEnv.getText().split(":");
            int row = tbl_integraciones.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
                return;
            }
            String value = tbl_integraciones.getModel().getValueAt(row, 0).toString();
            String name = tbl_integraciones.getModel().getValueAt(row, 1).toString() + ".iar";
            String version = tbl_integraciones.getModel().getValueAt(row, 4).toString();
            tbl_integraciones.clearSelection();
            System.out.println("souceEnvpart " + sourceEnvpart[1].trim());
            System.out.println("targetEnvPart " + targetEnvPart[1].trim());
            ExportarIntegracion hexportar = new ExportarIntegracion(value, name.replaceAll(" ", "_"), sourceEnvpart[1].trim(), version, targetEnvPart[1].trim());
            hexportar.start();
        }
    }

    //Listener para menu tabla lookups
    class PopupMenuListenerLookups implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            JMenuItem menuItem = (JMenuItem) e.getSource();
            String[] targetEnvPart = menuItem.getText().split(":");
            String[] souceEnvpart = lblCurEnv3.getText().split(":");
            int row = tblLookups.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
                return;
            }
            System.out.println("value = " + selectedEnv);

            String name = tblLookups.getModel().getValueAt(row, 1).toString();
            ExportarLookup hexportar = new ExportarLookup(name, selectedEnv.trim(), targetEnvPart[1].trim());
            hexportar.start();
        }
    }

    private void hideElemnets() {
        jpIntegrations.setVisible(false);
        jpConectores.setVisible(false);
        jpLookupTables.setVisible(false);
        pb_tst2.setVisible(false);
        pb_tst2_con.setVisible(false);
        pb_tst2_lookups.setVisible(false);
        lblPreloaderExport.setVisible(false);
        lblPreloaderUpdConector.setVisible(false);
        lblPreloaderLookups.setVisible(false);
    }

    private void cargarIntegraciones(String env, JTable table, JLabel lbl, JProgressBar pb, String status) {
        pb.setVisible(true);
        IntegrationModel im = new IntegrationModel();
        Map<String, Object> respuesta = im.getIntegrations(env, status);
        int total = (int) respuesta.get("total");
        lbl.setText("Total Integraciones: " + total);

        JsonArray list = (JsonArray) respuesta.get("integraciones");
//        System.out.println("list " + list);
        DefaultTableModel modeloTabla = new DefaultTableModel();
        // Agregar columnas a nuestro modelo de tabla
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("NAME");
        modeloTabla.addColumn("CODE");
        modeloTabla.addColumn("STATUS");
        modeloTabla.addColumn("ENV");
        modeloTabla.addColumn("VERSION");
        for (JsonElement jsonElement : list) {
            JsonObject jsonObject = jsonElement.getAsJsonObject();
            String ID = jsonObject.get("id").getAsString();
            String NAME = jsonObject.get("name").getAsString();
            String STATUS = jsonObject.get("status").getAsString();
            String CODE = jsonObject.get("code").getAsString();
            String VERSION = jsonObject.get("version").getAsString();
            modeloTabla.addRow(new Object[]{ID, NAME, CODE, STATUS, env, VERSION});
        }
// Asignar el modelo de tabla a nuestro JTable
        table.setModel(modeloTabla);
        table.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        table.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        table.getColumnModel().getColumn(0).setPreferredWidth(0);
        table.getColumnModel().getColumn(0).setMaxWidth(0);
        table.getColumnModel().getColumn(0).setMinWidth(0);
        table.getColumnModel().getColumn(3).setMaxWidth(150);
        table.getColumnModel().getColumn(3).setMinWidth(150);
        table.getColumnModel().getColumn(4).setMaxWidth(120);
        table.getColumnModel().getColumn(4).setMinWidth(120);

        table.setModel(modeloTabla);
        pb.setVisible(false);
        lblinfotst2.setText("");

    }

    //Hilos
    public class MiHilo extends Thread {

        String ambiente;
        String status;
        JTable table;
        JLabel lbl;
        JProgressBar pb;

        public MiHilo(String ambiente, JTable table, JLabel lbl, JProgressBar pb, String status) {
            this.ambiente = ambiente;
            this.table = table;
            this.lbl = lbl;
            this.pb = pb;
            this.status = status;
        }

        @Override
        public void run() {
            cargarIntegraciones(ambiente, table, lbl, pb, status);
        }
    }

    //Hilos
    public class MiHiloCon extends Thread {

        String ambiente;
        String status;

        public MiHiloCon(String ambiente, String status) {
            this.ambiente = ambiente;
            this.status = status;
        }

        @Override
        public void run() {
            cargarConectores(ambiente, status);
        }
    }

    public class HiloLookups extends Thread {

        String ambiente;
        String status;

        public HiloLookups(String ambiente, String status) {
            this.ambiente = ambiente;
            this.status = status;
        }

        @Override
        public void run() {
            cargaLookups(ambiente, status);
        }
    }

    public class ExportarIntegracion extends Thread {

        String ambienteOrigen;
        String ambienteDestino;
        String id;
        String nombre;
        String version;

        public ExportarIntegracion(String id, String nombre, String ambienteOrigen, String version, String ambienteDestino) {
            this.ambienteOrigen = ambienteOrigen;
            this.ambienteDestino = ambienteDestino;
            this.id = id;
            this.nombre = nombre;
            this.version = version;
        }

        @Override
        public void run() {
            lblinfotst2.setText("Exportando integración..");
            lblPreloaderExport.setVisible(true);
            OicRestApi oic = new OicRestApi();
            boolean r = oic.exportIntegration(id, nombre, ambienteOrigen);
            lblPreloaderExport.setVisible(false);
            lblinfotst2.setText("");
            if (r) {
                ImportarIntegracion hiloImportar = new ImportarIntegracion(id, nombre, ambienteDestino, version);
                hiloImportar.start();
            }
        }
    }

    public class ImportarIntegracion extends Thread {

        String ambiente;
        String id;
        String nombre;
        String version;

        public ImportarIntegracion(String id, String nombre, String ambiente, String version) {
            this.ambiente = ambiente;
            this.id = id;
            this.nombre = nombre;
            this.version = version;

        }

        @Override
        public void run() {
            //Refrescar el copnector con las credenciales
            //Activar integarcione
            lblinfotst2.setText("Importando integración...");
            lblPreloaderExport.setVisible(true);
            OicRestApi oic = new OicRestApi();
            int response = oic.importFileOIC(nombre, ambiente, "POST", "integrations");
            Map<String, Object> r;
            if (response == 200) {
                lblinfotst2.setText("Activando integración...");
                r = oic.activateDeactivateIntg(id, ambiente);
                responseMessage(r.get("response_code").toString(), r.get("response"), "");
            }
            if (response == 409) {
                int result = JOptionPane.showConfirmDialog(MainForm.this, "¿La integración " + nombre + " V(" + version + ") ya existe, desea reemplazarla?",
                        "Confirmación..!",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    response = oic.importFileOIC(nombre, ambiente, "PUT", "integrations");
                    System.out.println("response update int ------------>" + response);
                    if (response == 204) {
                        lblinfotst2.setText("Activando integración...");
                        r = oic.activateDeactivateIntg(id, ambiente);
                        responseMessage(r.get("response_code").toString(), r.get("response"), "");
                    }
                }
            }
            lblinfotst2.setText("");
            lblPreloaderExport.setVisible(false);
        }
    }

    public void responseMessage(String code, Object response, String intId) {
        String message = Utils.responseMessage(code);
        message = message.replace("&&", intId);
        if (code.equals("500")) {
            message += "\n" + response.toString();
        }
        JOptionPane.showMessageDialog(MainForm.this, message, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }

    //Hilo configura conectores
    public class ConfigConector extends Thread {

        String ambiente;
        String id;
        int option;

        public ConfigConector(String id, String ambiente, int option) {
            this.ambiente = ambiente;
            this.id = id;
            this.option = option;
        }

        @Override
        public void run() {
            Map<String, Object> r = null;
            lblPreloaderUpdConector.setVisible(true);
            ConectoresModel cm = new ConectoresModel();
            if (option == 1) {
                lblinfotstCon.setText("Actualizando credenciales");
                r = cm.updateConectionCredentials(ambiente, id);
            }
            if (option == 2) {
                lblinfotstCon.setText("Test de Conector");
                r = cm.testConection(ambiente, id);
            }
            String responseCode = r.get("response_code").toString() + "-" + option;
            lblPreloaderUpdConector.setVisible(false);
            responseMessage(responseCode, r.get("response"), id);
            lblinfotstCon.setText("");
//            System.out.println("r = " + responseCode);
        }
    }

    private void cargarConectores(String env, String status) {

        pb_tst2_con.setVisible(true);
        ConectoresModel cm = new ConectoresModel();
        Map<String, Object> respuesta = cm.getConections(env, status);
        int total = (int) respuesta.get("total");
        lboConectorsTST2.setText("Total Conectores: " + total);

        JsonArray list = (JsonArray) respuesta.get("conectores");
        DefaultTableModel modeloTabla = new DefaultTableModel();
//        System.out.println("Lista " + list);
        // Agregar columnas a nuestro modelo de tabla
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("NAME");
        modeloTabla.addColumn("STATUS");
        modeloTabla.addColumn("ENV");
        for (JsonElement jsonElement : list) {
            JsonObject jsonObject = jsonElement.getAsJsonObject();
            String ID = jsonObject.get("id").getAsString();
            String NAME = jsonObject.get("name").getAsString();
            String STATUS = jsonObject.get("status").getAsString();
            modeloTabla.addRow(new Object[]{ID, NAME, STATUS, env});
        }
// Asignar el modelo de tabla a nuestro JTable
        tblConectTST2.setModel(modeloTabla);
        tblConectTST2.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblConectTST2.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tblConectTST2.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblConectTST2.getColumnModel().getColumn(0).setMaxWidth(0);
        tblConectTST2.getColumnModel().getColumn(0).setMinWidth(0);
        tblConectTST2.getColumnModel().getColumn(3).setMaxWidth(150);
        tblConectTST2.getColumnModel().getColumn(3).setMinWidth(150);
//        tblConectTST2.getColumnModel().getColumn(4).setMaxWidth(120);
//        tblConectTST2.getColumnModel().getColumn(4).setMinWidth(120);

        tblConectTST2.setModel(modeloTabla);
        pb_tst2_con.setVisible(false);
        lblinfotst2.setText("");

    }

    private void cargaLookups(String env, String status) {

        pb_tst2_lookups.setVisible(true);
        LookupsModel lm = new LookupsModel();
        Map<String, Object> respuesta = lm.getLookups(env, status);
        int total = (int) respuesta.get("total");
        lblLookups.setText("Total Lookups: " + total);

        JsonArray list = (JsonArray) respuesta.get("lookups");
        DefaultTableModel modeloTabla = new DefaultTableModel();
//        System.out.println("Lista " + list);
//        System.exit(0);
//         Agregar columnas a nuestro modelo de tabla
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("NAME");
        modeloTabla.addColumn("STATUS");
        modeloTabla.addColumn("ENV");
        for (JsonElement jsonElement : list) {
            JsonObject jsonObject = jsonElement.getAsJsonObject();
            String ID = jsonObject.get("id").getAsString();
            String NAME = jsonObject.get("name").getAsString();
            String STATUS = jsonObject.get("status").getAsString();
            modeloTabla.addRow(new Object[]{ID, NAME, STATUS, env});
        }
// Asignar el modelo de tabla a nuestro JTable
        tblLookups.setModel(modeloTabla);
        tblLookups.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tblLookups.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tblLookups.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblLookups.getColumnModel().getColumn(0).setMaxWidth(0);
        tblLookups.getColumnModel().getColumn(0).setMinWidth(0);
        tblLookups.getColumnModel().getColumn(3).setMaxWidth(150);
        tblLookups.getColumnModel().getColumn(3).setMinWidth(150);
//        tblConectTST2.getColumnModel().getColumn(4).setMaxWidth(120);
//        tblConectTST2.getColumnModel().getColumn(4).setMinWidth(120);

        tblLookups.setModel(modeloTabla);
        pb_tst2_lookups.setVisible(false);
        lblinfotstLookups.setText("");

    }

    public class ExportarLookup extends Thread {

        String ambienteSrc;
        String ambienteTarget;
        String nombre;

        public ExportarLookup(String nombre, String ambiente, String ambienteTarget) {
            this.ambienteSrc = ambiente;
            this.ambienteTarget = ambienteTarget;
            this.nombre = nombre;
        }

        @Override
        public void run() {
            lblinfotstLookups.setText("Exportando lookup..");
            lblPreloaderLookups.setVisible(true);
            LookupsModel lm = new LookupsModel();
            boolean r = lm.exportLookup(nombre, ambienteSrc);
            lblPreloaderLookups.setVisible(false);
            lblinfotstLookups.setText("");
            if (r) {
                lblinfotstLookups.setText("Importando Lookup...");
                lblPreloaderLookups.setVisible(true);
                OicRestApi oic = new OicRestApi();
                int response = lm.importLookup(nombre, ambienteTarget, "POST", "lookups");
                System.out.println("response " + response);
                if (response == 409) {
                    int result = JOptionPane.showConfirmDialog(MainForm.this, "¿La Lookup Table " + nombre + " ya existe, desea reemplazarla?",
                            "Confirmación..!",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE);
                    if (result == JOptionPane.YES_OPTION) {
                        response = lm.importLookup(nombre, ambienteTarget, "PUT", "lookups");
                    }
                }
                JOptionPane.showMessageDialog(MainForm.this, Utils.responseMessage(Integer.toString(response) + "-3"), "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                lblinfotstLookups.setText("");
                lblPreloaderLookups.setVisible(false);
                //Pendiente preguntar si se desea remplazar la lookup
            }
        }
    }

}
